### ISSUE TITLE
what does the u mean in Python34u?

### ISSUE THREAD

**Issue by qwcode** [iuscommunity-pkg/python34u#1]

**Comment by carlwgeorge** [comment]
Howdy @qwcode,

IUS stands for "**I**nline with **U**pstream **S**table".  We continually update our packages to the latest stable upstream versions.  The u in our package names stands for "**U**pstream" as well.  There is a bit of a backstory to using that naming convention; I just got done explaining it [here](https://github.com/iuscommunity/ius.io/blob/master/docs/Philosophy.md#naming-convention), which is the markdown source for our soon-to-be-launched website overhaul.

**Comment by qwcode** [comment]
thanks  :  )
